#NAME: Marie Chu
#EMAIL: mariechu@ucla.edu
#UID: 905116878

lab4b: lab4.c
	./compile.sh
sources = lab4.c README Makefile script.sh compile.sh

dist: 
	tar -czf lab4b-905116878.tar.gz $(sources)
clean:
	rm -f *tar.gz lab4b 

