#NAME: Marie Chu
#EMAIL: mariechu@ucla.edu
#UID: 905116878 

lab3b: lab3b.py
	rm -f lab3b
	ln -s lab3b.py lab3b
	chmod +x lab3b

sources = lab3b.py README Makefile

dist: 
	tar -czf lab3b-905116878.tar.gz $(sources)
clean:
	rm -f *tar.gz lab3b 

