#NAME: Marie Chu
#EMAIL: mariechu@ucla.edu
#UID: 905116878 

sources = Makefile README my_beaglebone.jpg connected.png copy.png build_run.png git.png

dist: 
	tar -czf lab4a-905116878.tar.gz $(sources)

